### Testing

In [ ]:
%cd ..

In [5]:
import pandas as pd
import utils
import numpy as np
from sklearn.model_selection import train_test_split


In [47]:
xy_df_sub1_new_combined = pd.read_csv('data/xy_df/xy_df_sub1_weather_full.csv')
without_extra_columns = xy_df_sub1_new_combined.drop([ 'latitude', 'longitude', 'Start Year', 'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day'], axis=1)
x = without_extra_columns.drop(without_extra_columns.filter(regex='target').columns, axis=1)#drop target col
x = x.select_dtypes(['number'])#drop index col
y = without_extra_columns.filter(regex='target') #filter to cols containing target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
x_train = x_train.drop(['label', 'Unnamed: 0'], axis=1) # uncomment these next two lines to keep flood data in stats
x_test = x_test.drop(['label', 'Unnamed: 0'], axis=1) # 

In [35]:
results = {}

In [38]:
def stats_only():
	y_pred, y_pred_prob = utils.run_xgb(x_train.iloc[:, 2:27], np.ravel(y_train), x_test.iloc[:, 2:27])
	results['stats only'] = utils.get_scores_clf(y_test, y_pred_prob)

stats_only()

running xgb...
[10, 20, 65]
Train AUC:  0.980857895671155
{'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100, 'scale_pos_weight': 10}
maximum f1 score, thres 0.6488566549213951 0.7
auc, f1, accu, accu_bl, precision, recall=  0.9694155983875686 0.6488566549213951 0.9734097658678086 0.688030503158027 0.11058279692579132 0.3936651583710407
[[14007   251]
 [  134    87]]


In [48]:
def nlp_only():
	y_pred, y_pred_prob = utils.run_xgb(x_train.iloc[:, 27:155], np.ravel(y_train), x_test.iloc[:, 27:155])
	results['nlp only'] = utils.get_scores_clf(y_test, y_pred_prob)

nlp_only()

running xgb...
[10, 20, 65]
Train AUC:  0.8753095143386883
{'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 100, 'scale_pos_weight': 20}
maximum f1 score, thres 0.5563224804334327 0.6
auc, f1, accu, accu_bl, precision, recall=  0.7042259041363774 0.5559558099639905 0.9603563782029145 0.5856255026153453 0.032088957145297796 0.19909502262443438
[[13861   397]
 [  177    44]]


In [ ]:
def weather_only():
	y_pred, y_pred_prob = utils.run_xgb(x_train.iloc[:, 155:], np.ravel(y_train), x_test.iloc[:, 155:])
	results['weather only'] = utils.get_scores_clf(y_test, y_pred_prob)

weather_only()

running xgb...
[10, 20, 65]
Train AUC:  0.9990863676794355
{'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 100, 'scale_pos_weight': 10}
maximum f1 score, thres 0.5377543506730906 0.4
auc, f1, accu, accu_bl, precision, recall=  0.7093306036334923 0.5002709577651027 0.9807307134470613 0.5269219344351571 0.023469274442286067 0.058823529411764705
[[14187    71]
 [  208    13]]


In [51]:
def stats_nlp():
	y_pred, y_pred_prob = utils.run_xgb(x_train.iloc[:, 2:155], np.ravel(y_train), x_test.iloc[:, 2:155])
	results['stats nlp'] = utils.get_scores_clf(y_test, y_pred_prob)

stats_nlp()

running xgb...
[10, 20, 65]
Train AUC:  0.9888364092415316
{'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100, 'scale_pos_weight': 10}
maximum f1 score, thres 0.6394274104608029 0.6
auc, f1, accu, accu_bl, precision, recall=  0.9632748844976449 0.6353185734470012 0.9649837695973479 0.7282997113948572 0.11148433165336347 0.4841628959276018
[[13865   393]
 [  114   107]]
